spring:
  application:
    name: usian-content-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
      - 192.168.88.129:7001
      - 192.168.88.129:7002
      - 192.168.88.129:7003
      - 192.168.88.129:7004
      - 192.168.88.129:7005
      - 192.168.88.129:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#指定mapper映射文件位置以及泛型包位置
mybatis:
  typeAliasesPackage: com.usian.pojo
  mapperLocations: classpath:mapper/*.xml
  #  开始驼峰转下划线
  configuration:
    map-underscore-to-camel-case: true