spring:
  application:
    name: usian-item-web
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.88.129:22122

#开启熔断
feign:
  hystrix:
   enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 5
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 5000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000