spring:
  application:
    name: usian-search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    elasticsearch:
      cluster-nodes: 192.168.88.129:9200
  rabbitmq:
    host: 192.168.88.129
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#指定mapper映射文件位置以及泛型包位置
mybatis:
  typeAliasesPackage: com.usian.pojo
  mapperLocations: classpath:mapper/*.xml
  #  开始驼峰转下划线
  configuration:
    map-underscore-to-camel-case: true
