spring:
  application:
    name: usian-sso-web
  rabbitmq:
    host: 192.168.88.129
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
server:
  port: 8099
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/