spring:
  application:
    name: usian-sso-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.88.129
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    cluster:
      nodes:
      - 192.168.88.129:7001
      - 192.168.88.129:7002
      - 192.168.88.129:7003
      - 192.168.88.129:7004
      - 192.168.88.129:7005
      - 192.168.88.129:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
server:
  port: 8098
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/